services:
  portainer:
    image: portainer/portainer-ce:2.25.1
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/sock:/var/run/sock
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    deploy:
      mode: replicated # Nur den Portainer-Service als Replikat bereitstellen
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  agent:
    image: portainer/agent:2.25.1
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent # Swarm Communication
    volumes:
      - /var/run/sock:/var/run/sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global # Agent auf allen Nodes ausrollen
      placement:
        constraints:
          - node.platform.os == linux
volumes:
  portainer_data:
