commands:
  - index: 1
    description: "Joining Worker Nodes to Swarm"
    command: "multipass exec {vm_instance} -- docker swarm join --token {swarm_token} {swarm_manager_ip}:{swarm_manager_port}"
    runner: "async"
    command_type: "vm"
    vm_type:
      - "worker"