vms:
  - vm_instance: "swarm-manager"
    vm_type: "manager"
    ipaddress: "192.168.1.2"
    gateway: "192.168.1.1"
    memory: "4G"
    disk: "20G"

  - vm_instance: "swarm-worker-1"
    vm_type: "worker"
    ipaddress: "192.168.1.3"
    gateway: "192.168.1.1"
    memory: "8G"
    disk: "50G"

  - vm_instance: "swarm-worker-2"
    vm_type: "worker"
    ipaddress: "192.168.1.4"
    gateway: "192.168.1.1"
    memory: "2G"
    disk: "10G"
