services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8082:8080"
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8083:8080"
    restart: always
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
      # API_URL: ""

  swagger-api:
    restart: always
    image: danielgtaylor/apisprout
    ports:
      - "8084:8000"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    command: /openapi.json
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout

  swagger-nginx:
    restart: always
    image: nginx:mainline-alpine
    ports:
      - "8087:8084"
    volumes:
      - /mnt/d/Projects/bomfile/docker/compose/swagger/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      swagger_link:
        aliases:
          - local.swagger.api

networks:
  swagger_link: