services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "127.0.0.1:8082:8080"
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "127.0.0.1:8083:8080"
    restart: always
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
      # API_URL: ""

  swagger-api:
    restart: always
    image: danielgtaylor/apisprout
    ports:
      - "127.0.0.1:8084:8000"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    command: /openapi.json
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout

  swagger-nginx:
    restart: always
    image: 127.0.0.1:5000/swagger-nginx:latest
    ports:
      - "127.0.0.1:8087:8084"
    depends_on:
      - swagger-api
    networks:
      swagger_link:
        aliases:
          - local.swagger.api
networks:
  swagger_link: