services:
  portainer:
    image: portainer/portainer-ce:2.21.0
    restart: always
    volumes:
      - /mnt/c/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000