services:
  portainer:
    image: portainer/portainer-ce:2.25.1
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:9000:9000"
volumes:
  portainer_data: