#cloud-config
network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4: no
      addresses:
        - {{ADDRESS}}/24
      routes:
        - to: 0.0.0.0/0
          via: {{GATEWAY}}
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
