services:
  nexus:
    image: sonatype/nexus3:3.75.1

    container_name: 'nexus3'
    restart: always
    volumes:
      - nexus-data:/sonatype-work:latest
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8085:8085"
      - "127.0.0.1:5000:5000"
volumes:
  nexus-data: