== Setup docker swarm on local ubuntu system

Bevor das Setup laufen kann, müssen am wsl subsystem einige Einstellungen vorgenommen werden.
In diesem Installationsprozess wird **multipass** verwendet.
Dieses Programm ermöglicht es, dass virtuelle Instanzen, des aktuellen Linux-Systems erstellt werden.

Das mulitpass wird mit

----
sudo snap install multipass
----

installiert.

----
sudo apt update && sudo apt install -y socat
----

----
sudo socat TCP-LISTEN:80,fork TCP:10.34.157.122:80
nohup sudo socat TCP-LISTEN:80,fork TCP:10.34.157.122:80 &
----

----
netsh interface portproxy delete v4tov4 listenport=80 listenaddress=0.0.0.0
netsh interface portproxy add v4tov4 listenport=80 listenaddress=0.0.0.0 connectport=80 connectaddress=172.25.81.206

----

Im setup.sh wird dann der docker Ordner auf das Linux-Subsystem in ein echtes ext4-Format kopiert.

To generate within the intellij console, you have to run intellij as administrator oder sudo

Run the setup.sh script below swarm.
To Join into multipass shell swarm-manager

to clean up multipass stop <vm-name> multipass delete <vm-name> multipass purge

multipass delete swarm-worker-1 swarm-worker-2 swarm-manager | multipass purge | multipass list multipass stop swarm-worker-1 swarm-worker-2 swarm-manager multipass delete swarm-worker-1 swarm-worker-2 swarm-manager | multipass purge

multipass purge

multipass info swarm-manager | grep "IPv4"

multipass launch --name swarm-manager --cloud-init ./cloud-config.yaml multipass launch --name swarm-worker-1 --cloud-init ./cloud-config.yaml multipass launch --name swarm-worker-2 --cloud-init ./cloud-config.yaml

== Install the portainer

The portainer app is the local webinterface to have an overview of the installed system.
See documentation of portainer. +

At first run this script und the portainer will be installed on your docker system.

----
 ./docker/prepare/prepare_portainer.sh
----

Open the portainer the first time and create the admin user.
The password and the user have to be set after open portainer the first time. +
If you do not want to change this values, keep the defaults.

----
 USER = admin
 PASSWORD = admin1234567890
----

After that you have got a fresh portainer system running without any other stuff.
Next step is to get life into the portainer.

== Terraforming light :)

If you have changed the user and password for your needs you got 2 ways to get the upload-script running.
At the first you use the parameter of the script:

----
 ./docker/compose/upload_all_stacks.sh
----

----
 -u username: Optional. Current is 'admin'.
 -p password: Optional. Current is 'admin1234567890'.
----

or you open the script and change the default values.

----
USERNAME="admin"
PASSWORD="admin1234567890"
----

and then happy running
----
 .docker/upload_all_stacks.sh
----

== The ports:

=== Portainer

http://localhost:9000[localhost:9000 portainer start]

USER: admin PASSWORD: admin1234567890

=== nexus

- https://help.sonatype.com/en/rest-apis.html[RestApi Help]
- http://localhost:8081/[localhost:8081/ nexus]
- http://localhost:8085/[localhost:8085/ nexus api]

For the password you have to log in into the docker container:

----
docker exec -it nexus-nexus-1 /bin/sh
cat /nexus-data/admin.password
----

User = admin Password = 4d4ac9ff-7daa-4b93-9cfa-fe391d94f100 (in my case)

=== swagger

- http://localhost:8082/[localhost:8082/ swagger-editor]
- http://localhost:8083/[localhost:8083/ swagger-ui ]

=== sonarqube

- http://localhost:9001/[localhost:9001/ sonarqube ]

USER: admin
PASSWORD: admin1

To run on linux or windows subsystem
echo 'vm.max_map_count=262144' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

echo '{"insecure-registries": ["127.0.0.1:5000"]}' | sudo tee /etc/docker/daemon.json > /dev/null sudo systemctl restart docker

=== Rabbit MQ

- http://localhost:5672/[localhost:5672/ rabbit api communication]
- http://localhost:15672/[localhost:15672/ rabbit UI  ]

USER: guest PASSWORD: guest